[env:seeed_xiao_esp32c6]
# platform = espressif32@~6.9.0
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino

monitor_speed = 115200

; Enable Zigbee in the ESP-IDF config
board_build.zigbee = yes

; Partition scheme with Zigbee NVRAM storage
board_build.partitions = zigbee.csv

lib_deps =
    adafruit/Adafruit PN532 @ ^1.3.0
    adafruit/Adafruit BusIO @ ^1.16.0

build_flags =
    -DCONFIG_ZB_ENABLED=1
    -DZIGBEE_MODE_ED=1
